language: node_js
node_js:
  - 6
os: 
  - linux
dist: trusty
before_install:
  - sudo apt-get install libssl0.9.8 libssl-dev liblua5.1-dev
  - sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.so /usr/lib/liblua.so
  - sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.1.a /usr/lib/liblua.a
install:
  - npm install -g bower
  - bower install